site_name: "FastAPI Application CICD Template"
site_description: "This is simple FastAPI application created using Uvicorn framework. It will also deploy the FastAPI demo application to the Cloud Run environment."

nav:
  - Introduction: index.md
  - FastAPI Application: fastapi/readme.md
  - Terraform Deployment: infra/readme.md

plugins:
  - techdocs-core

theme:
  name: material